require("plugins.packer")
require("plugins.file_explorer")
require("plugins.indent_guide")
require("plugins.lsp")
require("plugins.colorscheme")

require("plugins.golang")
require("plugins.terminal")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.comment")
require("plugins.autopair")
require("plugins.impatient")
require("plugins.whichkey")
require("plugins.telescope")
require("plugins.easymotion")
